/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackOrderIdRouteImport } from './routes/track.$orderId'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as ApiPublicHooksTelegramSetupRouteImport } from './routes/api/public/hooks/telegram-setup'
import { Route as ApiPublicHooksTelegramRouteImport } from './routes/api/public/hooks/telegram'
import { Route as ApiPublicHooksDailyProfitRouteImport } from './routes/api/public/hooks/daily-profit'
import { Route as ApiPublicHooksBalanceCheckRouteImport } from './routes/api/public/hooks/balance-check'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminOrdersRouteImport } from './routes/_authenticated/_admin/admin.orders'
import { Route as AuthenticatedAdminAdminBundlesRouteImport } from './routes/_authenticated/_admin/admin.bundles'
import { Route as AuthenticatedAdminAdminOrdersOrderIdRouteImport } from './routes/_authenticated/_admin/admin.orders_.$orderId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderIdRoute = TrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedOrdersRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksTelegramSetupRoute =
  ApiPublicHooksTelegramSetupRouteImport.update({
    id: '/api/public/hooks/telegram-setup',
    path: '/api/public/hooks/telegram-setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelegramRoute = ApiPublicHooksTelegramRouteImport.update({
  id: '/api/public/hooks/telegram',
  path: '/api/public/hooks/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyProfitRoute =
  ApiPublicHooksDailyProfitRouteImport.update({
    id: '/api/public/hooks/daily-profit',
    path: '/api/public/hooks/daily-profit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBalanceCheckRoute =
  ApiPublicHooksBalanceCheckRouteImport.update({
    id: '/api/public/hooks/balance-check',
    path: '/api/public/hooks/balance-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminOrdersRoute =
  AuthenticatedAdminAdminOrdersRouteImport.update({
    id: '/admin/orders',
    path: '/admin/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminBundlesRoute =
  AuthenticatedAdminAdminBundlesRouteImport.update({
    id: '/admin/bundles',
    path: '/admin/bundles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminOrdersOrderIdRoute =
  AuthenticatedAdminAdminOrdersOrderIdRouteImport.update({
    id: '/admin/orders_/$orderId',
    path: '/admin/orders/$orderId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/track/$orderId': typeof TrackOrderIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/admin/bundles': typeof AuthenticatedAdminAdminBundlesRoute
  '/admin/orders': typeof AuthenticatedAdminAdminOrdersRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/api/public/hooks/balance-check': typeof ApiPublicHooksBalanceCheckRoute
  '/api/public/hooks/daily-profit': typeof ApiPublicHooksDailyProfitRoute
  '/api/public/hooks/telegram': typeof ApiPublicHooksTelegramRoute
  '/api/public/hooks/telegram-setup': typeof ApiPublicHooksTelegramSetupRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminAdminOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/track/$orderId': typeof TrackOrderIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/admin/bundles': typeof AuthenticatedAdminAdminBundlesRoute
  '/admin/orders': typeof AuthenticatedAdminAdminOrdersRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/api/public/hooks/balance-check': typeof ApiPublicHooksBalanceCheckRoute
  '/api/public/hooks/daily-profit': typeof ApiPublicHooksDailyProfitRoute
  '/api/public/hooks/telegram': typeof ApiPublicHooksTelegramRoute
  '/api/public/hooks/telegram-setup': typeof ApiPublicHooksTelegramSetupRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminAdminOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/track/$orderId': typeof TrackOrderIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/_admin/admin/bundles': typeof AuthenticatedAdminAdminBundlesRoute
  '/_authenticated/_admin/admin/orders': typeof AuthenticatedAdminAdminOrdersRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/api/public/hooks/balance-check': typeof ApiPublicHooksBalanceCheckRoute
  '/api/public/hooks/daily-profit': typeof ApiPublicHooksDailyProfitRoute
  '/api/public/hooks/telegram': typeof ApiPublicHooksTelegramRoute
  '/api/public/hooks/telegram-setup': typeof ApiPublicHooksTelegramSetupRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_admin/admin/orders_/$orderId': typeof AuthenticatedAdminAdminOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard'
    | '/orders'
    | '/track/$orderId'
    | '/orders/$orderId'
    | '/admin/bundles'
    | '/admin/orders'
    | '/admin/users'
    | '/api/public/hooks/balance-check'
    | '/api/public/hooks/daily-profit'
    | '/api/public/hooks/telegram'
    | '/api/public/hooks/telegram-setup'
    | '/admin/'
    | '/admin/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard'
    | '/orders'
    | '/track/$orderId'
    | '/orders/$orderId'
    | '/admin/bundles'
    | '/admin/orders'
    | '/admin/users'
    | '/api/public/hooks/balance-check'
    | '/api/public/hooks/daily-profit'
    | '/api/public/hooks/telegram'
    | '/api/public/hooks/telegram-setup'
    | '/admin'
    | '/admin/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/orders'
    | '/track/$orderId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/_admin/admin/bundles'
    | '/_authenticated/_admin/admin/orders'
    | '/_authenticated/_admin/admin/users'
    | '/api/public/hooks/balance-check'
    | '/api/public/hooks/daily-profit'
    | '/api/public/hooks/telegram'
    | '/api/public/hooks/telegram-setup'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_admin/admin/orders_/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TrackOrderIdRoute: typeof TrackOrderIdRoute
  ApiPublicHooksBalanceCheckRoute: typeof ApiPublicHooksBalanceCheckRoute
  ApiPublicHooksDailyProfitRoute: typeof ApiPublicHooksDailyProfitRoute
  ApiPublicHooksTelegramRoute: typeof ApiPublicHooksTelegramRoute
  ApiPublicHooksTelegramSetupRoute: typeof ApiPublicHooksTelegramSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$orderId': {
      id: '/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/track/$orderId'
      preLoaderRoute: typeof TrackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/telegram-setup': {
      id: '/api/public/hooks/telegram-setup'
      path: '/api/public/hooks/telegram-setup'
      fullPath: '/api/public/hooks/telegram-setup'
      preLoaderRoute: typeof ApiPublicHooksTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram': {
      id: '/api/public/hooks/telegram'
      path: '/api/public/hooks/telegram'
      fullPath: '/api/public/hooks/telegram'
      preLoaderRoute: typeof ApiPublicHooksTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-profit': {
      id: '/api/public/hooks/daily-profit'
      path: '/api/public/hooks/daily-profit'
      fullPath: '/api/public/hooks/daily-profit'
      preLoaderRoute: typeof ApiPublicHooksDailyProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/balance-check': {
      id: '/api/public/hooks/balance-check'
      path: '/api/public/hooks/balance-check'
      fullPath: '/api/public/hooks/balance-check'
      preLoaderRoute: typeof ApiPublicHooksBalanceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/orders': {
      id: '/_authenticated/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/bundles': {
      id: '/_authenticated/_admin/admin/bundles'
      path: '/admin/bundles'
      fullPath: '/admin/bundles'
      preLoaderRoute: typeof AuthenticatedAdminAdminBundlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/orders_/$orderId': {
      id: '/_authenticated/_admin/admin/orders_/$orderId'
      path: '/admin/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedAdminAdminOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminBundlesRoute: typeof AuthenticatedAdminAdminBundlesRoute
  AuthenticatedAdminAdminOrdersRoute: typeof AuthenticatedAdminAdminOrdersRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
  AuthenticatedAdminAdminOrdersOrderIdRoute: typeof AuthenticatedAdminAdminOrdersOrderIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminBundlesRoute: AuthenticatedAdminAdminBundlesRoute,
  AuthenticatedAdminAdminOrdersRoute: AuthenticatedAdminAdminOrdersRoute,
  AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  AuthenticatedAdminAdminOrdersOrderIdRoute:
    AuthenticatedAdminAdminOrdersOrderIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TrackOrderIdRoute: TrackOrderIdRoute,
  ApiPublicHooksBalanceCheckRoute: ApiPublicHooksBalanceCheckRoute,
  ApiPublicHooksDailyProfitRoute: ApiPublicHooksDailyProfitRoute,
  ApiPublicHooksTelegramRoute: ApiPublicHooksTelegramRoute,
  ApiPublicHooksTelegramSetupRoute: ApiPublicHooksTelegramSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
